version: '3.8'
services:
  mariadb:
    image: mariadb:11.8.2
    container_name: sde_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - sde_mariadb:/var/lib/mysql

volumes:
  sde_mariadb:
